name: 'Build Consensys doc'
description: 'Builds the Consensys documentation using a Docker container with all dependencies installed'
branding:
  icon: 'upload-cloud'
  color: 'blue'

runs:
  using: 'docker'
  image: 'Dockerfile'
