# Copyright 2020 ConsenSys Software Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
# an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
# specific language governing permissions and limitations under the License.

# Project information
site_name: !ENV [SITE_NAME, 'Doctools']
site_description: !ENV [SITE_DESCRIPTION, 'Doctools documentation template']

# Software Repository
repo_name: !ENV [REPOS_NAME, 'Consensys/doctools.template-site']
repo_url: !ENV [REPOS_URL, 'https://github.com/Consensys/doctools.template-site']

# Project information
site_url: !ENV [SITE_URL, 'http://0.0.0.0:8000/']
site_author: !ENV [COMPANY ,'ConsenSys']
copyright: !ENV [COPYRIGHT ,'This documentation is hosted by <a href="https://consensys.net/">ConsenSys</a> and licensed under Apache 2.0 license']

extra:
  debug: !ENV [DEBUG , false]
  version:
    number: !ENV [VERSION ,'latest']
    switch: !ENV [VERSION_SWITCH , false]
  logo_is_text: !ENV [LOGO_IS_TEXT ,false]
  latest_version_warning:
    text: 'You are reading the development version of this documentation and
    some displayed features may not be available in the stable release.
    You can switch to stable version using the switch in the header.'
  analytics:
    provider: gtm
    gtmid: !ENV GTM_ID
  # TODO Add a version file path here to be used in version JS
  social:
    - icon: fontawesome/brands/discord
      link: !ENV [SOCIAL_DISCORD ,'https://discord.gg/5U9Jwp7']
    - icon: fontawesome/solid/envelope
      link: !ENV [SOCIAL_EMAIL ,'mailto:quorum@consensys.net']
    - icon: material/web
      link: !ENV [SOCIAL_WEB ,'https://consensys.net/quorum/developers']
theme:
  name: material
  custom_dir: /common/custom_theme
  language: !ENV [LANGUAGE, 'en']
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: consensys
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: consensys-dark
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  logo: 'assets/logo.svg'
  favicon: 'assets/favicon.svg'
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes

extra_css:
  - assets/stylesheets/custom.css
  - assets/stylesheets/version.css
  - https://fonts.googleapis.com/icon?family=Material+Icons
extra_javascript:
  - assets/javascripts/version.js
  - assets/javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - assets/javascripts/accessiBe.js

markdown_extensions:
  - toc:
      permalink: true
      permalink_title: Link to this section
      toc_depth: 4
  - codehilite
  - pymdownx.tabbed
  - pymdownx.superfences
  - markdown_include.include:
      base_path: docs
  - admonition
  - footnotes
  - def_list
  - attr_list
  - abbr
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - meta
  - smarty
  - plantuml_markdown:
      server: http://www.plantuml.com/plantuml

plugins:
  search:
    lang: en
    separator: '[\s\-\.\_]+'
    prebuild_index: true
  markdownextradata: {}
#  minify:
#    minify_html: true
#    minify_js: true
#    htmlmin_opts:
#      remove_comments: true
# uncomment to exclude a folder in /docs from final render.
# useful for include files
#  - exclude:
#      glob:
#        - cmd/*
  git-revision-date-localized:
    locale: !ENV [LANGUAGE, 'en']
  mkdocs-video:
    css_style:
      weight: "50%"
