# SPDX-License-Identifier: Apache-2.0
---
name: 'Delete PR preview'
description: 'Composite action to delete PR preview'

runs:
  using: "composite"
  steps:
    - name: generate PR slug
      shell: sh
      id: generate_pr_slug
      run: echo "::set-output name=slug::PR-${{ github.event.number }}"

    - name: Delete preview
      shell: sh
      run: |
        rm -Rf "${{ steps.generate_pr_slug.outputs.slug }}"

    - name: Commit and push to gh-pages
      shell: sh
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
        git commit -am "Automated deletion"
        git push

    - name: Remove comment to preview doc link
      uses: marocchino/sticky-pull-request-comment@39c5b5dc7717447d0cba270cd115037d32d28443 #v2.2.0
      with:
        header: preview
        delete: true

