---
name: 'Build and publish latest doc'
description: 'Composite action to build and publish latest doc site'
inputs:
  AWS_ACCESS_KEY_ID:
    description: 'AWS secrets id'
    required: true
  AWS_SECRET_ACCESS_KEY:
    description: 'AWS secrets key'
    required: true
  SITE_URL_BASE:
    description: 'Hosting URL base'
    required: false
    default: "https://consensys.net/docs/"

runs:
  using: "composite"
  steps:
    - name: set environment vars from .env file
      uses: c-py/action-dotenv-to-setenv@a6380f4d905f42adb7c065db63e6d66d75b971ad #v3
      with:
        env-file: '.env'

    - name: Build doc
      uses: ConsenSys/doctools.action-builder/actions/build@main
      with:
        # TODO see if it's possible to use join() here
        # https://docs.github.com/en/actions/learn-github-actions/expressions#join
        SITE_URL: ${{ inputs.SITE_URL_BASE }}${{ env.PROJECT }}/${{ env.LANGUAGE }}/${{ env.LATEST_VERSION }}/
        VERSION: ${{ env.LATEST_VERSION }}

    - name: Publish to AWS
      uses: ConsenSys/doctools.action-builder/actions/publish-aws@main
      with:
        VERSION: ${{ env.LATEST_VERSION }}
        AWS_ACCESS_KEY_ID: ${{ inputs.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
