# SPDX-License-Identifier: Apache-2.0
---
name: 'Build and publish PR preview'
description: 'Composite action Build and publish PR preview doc site'

inputs:
  LANGUAGE:
    description: 'doc language to build'
    required: false
    default: en
  BRANCH:
    description: 'doc language to build'
    required: false
    default: gh-pages
  PREVIEW_DOMAIN:
    description: 'doc preview domain if not default public one'
    required: false

runs:
  using: "composite"
  steps:
    - name: Get additional Github env vars # vars from Github env, can not be modified by users
      uses: FranzDiebold/github-env-vars-action@b9b3a88cfa3ad9bde40c291143c28f918e2d1668 #v2.3.0

    - name: generate PR slug
      shell: sh
      id: generate_pr_slug
      run: echo "::set-output name=slug::PR-${{ github.event.number }}"

    - name: set default preview domain
      shell: sh
      run: echo "PREVIEW_DOMAIN=https://${{ env.CI_REPOSITORY_OWNER_SLUG }}.github.io/${{ env.CI_REPOSITORY_NAME }}/" >> $GITHUB_ENV

    - name: set custom preview domain if defined
      shell: sh
      env:
        preview_domain: ${{ inputs.PREVIEW_DOMAIN }}
      if: ${{ env.preview_domain != '' }}
      run: echo "PREVIEW_DOMAIN=${{env.preview_domain}}" >> $GITHUB_ENV

    - name: Build doc
      uses: ConsenSys/doctools.action-builder/actions/build@main
      with:
        SITE_ROOT: ${{env.PREVIEW_DOMAIN}}
        VERSION: ${{ steps.generate_pr_slug.outputs.slug }}
        LANGUAGE: ${{ inputs.LANGUAGE }}

    - name: Deploy Preview
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
        branch: ${{ inputs.BRANCH }} # The branch the action should deploy to.
        folder: site # The folder the action should deploy.
        target-folder: ${{ steps.generate_pr_slug.outputs.slug }}
        commit-message: Preview for ${{ steps.generate_pr_slug.outputs.slug }}
        single-commit: true

    - name: Add comment with link to preview doc
      uses: marocchino/sticky-pull-request-comment@39c5b5dc7717447d0cba270cd115037d32d28443 #v2.2.0
      with:
        header: preview
        recreate: true
        message: |
          [Doc preview for this PR #${{ github.event.number }} is available](${{env.PREVIEW_DOMAIN}}${{ steps.generate_pr_slug.outputs.slug }})
