# SPDX-License-Identifier: Apache-2.0
---
name: 'Build and publish PR preview'
description: 'Composite action Build and publish PR preview doc site'

inputs:
  LANGUAGE:
    description: 'doc language to build'
    required: false
    default: en

runs:
  using: "composite"
  steps:
    - name: Get additional Github env vars
      uses: FranzDiebold/github-env-vars-action@b9b3a88cfa3ad9bde40c291143c28f918e2d1668 #v2.3.0

    - name: Set PR_VERSION env vars
      shell: sh
      run: |
        echo "PR_VERSION=PR-${{ github.event.number }}" >> $GITHUB_ENV

    - name: Build doc
      uses: ConsenSys/doctools.action-builder/actions/build@main
      with:
        SITE_ROOT: https://${{ env.CI_REPOSITORY_OWNER_SLUG }}.github.io/${{ env.CI_REPOSITORY_NAME }}/
        VERSION: ${{ env.PR_VERSION }}
        LANGUAGE: ${{ inputs.LANGUAGE }}

    - name: Deploy Preview
      uses: JamesIves/github-pages-deploy-action@4
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: site # The folder the action should deploy.
        target-folder: ${{ env.PR_VERSION }}
        commit-message: Preview for ${{ env.PR_VERSION }}
        single-commit: true

    - name: Add comment with link to preview doc
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        header: preview
        recreate: true
        message: |
          [Doc preview for this PR #${{ github.event.number }} is available](https://${{ env.CI_REPOSITORY_OWNER }}.github.io/${{ env.CI_REPOSITORY_NAME }}/${{ env.PR_VERSION }})
