name: Build and publish Docker image

on:
  push:
    branches:
      - main
  release:
    types: [published]
    branches: [main]

env:
  IMAGE_NAME: doctools-builder
  IMAGE_LATEST_TAG: latest
  REGISTRY: ghcr.io

jobs:
  publish_docker:
    name: Build and push Docker image
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        shell: sh
        run: |
          docker build . \
          --tag $IMAGE_NAME \
          --build-arg VERSION="${GITHUB_REF#refs/*/}" \
          --build-arg REVISION="${GITHUB_SHA}" \
          --build-arg GITHUB_WORKFLOW="${GITHUB_WORKFLOW}" \
          --build-arg GITHUB_RUN_ID="${GITHUB_RUN_ID}"

      - name: Image minimal test
        shell: sh
        run: |
          docker run --rm \
          --env-file ./tests/.env \
          -v ${PWD}:/workspace \
          -w /workspace \
          $IMAGE_NAME \
          build -s \
          --config-file /workspace/tests/mkdocs.yml

      - name: Login to GitHub Container Registry
        #https://github.com/docker/login-action/releases/tag/v1.10.0
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image name
        shell: sh
        run: |
          IMAGE_ID=$REGISTRY/${{ github.repository_owner }}/$IMAGE_NAME
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_ENV

      - name: Push latest
        shell: sh
        run: |
          docker tag $IMAGE_NAME $IMAGE_ID:$IMAGE_LATEST_TAG
          docker push $IMAGE_ID:$IMAGE_LATEST_TAG

      - name: Push tagged release
        if: github.event_name == 'release' && github.event.action == 'published'
        shell: sh
        run: |
          IMAGE_TAG=${GITHUB_REF#refs/*/}
          docker tag $IMAGE_NAME $IMAGE_ID:$IMAGE_TAG
          docker push $IMAGE_ID:$IMAGE_TAG

      - name: Test building doc using our action
        uses: ConsenSys/doctools.action-builder/actions/build@main
        with:
          SITE_ROOT: 'https://example.org' #fake site, just testing but cannot be empty
          ENV_FILE: tests/.env
          MKDOCS_CONFIG: /workspace/tests/mkdocs.yml
