name: Build and publish Docker image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: doctools-builder
  IMAGE_LATEST_TAG: latest
  REGISTRY: ghcr.io

jobs:
  publish_docker:
    name: Build and push Docker image
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        shell: sh
        run: docker build . --file Dockerfile --tag $IMAGE_NAME --label "runnumber=${GITHUB_RUN_ID}"

      - name: Image minimal test
        shell: sh
        run: docker run --rm -v ${PWD}:/docs -w /docs $IMAGE_NAME build -s

      - name: Login to GitHub Container Registry
        #https://github.com/docker/login-action/releases/tag/v1.10.0
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push image
        shell: sh
        run: |
          IMAGE_ID=$REGISTRY/${{ github.repository_owner }}/$IMAGE_NAME
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          echo IMAGE_ID=$IMAGE_ID

          # Publish latest always
          docker tag $IMAGE_NAME $IMAGE_ID:$IMAGE_LATEST_TAG
          docker push $IMAGE_ID:$IMAGE_LATEST_TAG

          IMAGE_TAG=${GITHUB_REF#refs/*/}
          # Publish release only if tag exists
          if [ "$IMAGE_TAG" != "" ]; then
            docker tag $IMAGE_NAME $IMAGE_ID:$IMAGE_TAG
            docker push $IMAGE_ID:$IMAGE_TAG
          fi

      - name: Test building doc using our action
        uses: ConsenSys/doctools.action-builder/actions/build@main
        with:
          SITE_URL: 'https://consensys.net/docs/action-builder-test' #fake site, just testing
          VERSION: ${{ env.IMAGE_LATEST_TAG }}
