on:
  push:
    branches:
      - main

jobs:
  build-with-docker:
    name: Build doc with Docker
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nicolasmassart/doctools:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: mkdocs build -s
      - name: Upload built site
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: site
          path: site
          if-no-files-found: error
          retention-days: 1
  test-build:
    needs: build-with-docker
    name: Test built site
    runs-on: ubuntu-latest
    steps:
      - name: Download built site
        uses: actions/download-artifact@v2
        with:
          name: site
          path: site
      - name: test
        run: |
          ls -la
          cd site
          ls -la
